// PRIMA TARIF — jazykovo neutrálne fakty z content packu v0.1 (content/packs/tarif.md)
// + overenia z docs/RESEARCH-TARIF.md. `null` = PRIMA doplní (hosťovi sa neukáže).
export default {
  propertyId: 'p_tarif',
  packVersion: '0.1',
  beds: 1206,
  roomType: '3-bed',
  fridgeInRoom: true,
  wifi: { ssid: 'PRIMA-TARIF', password: null, note5g: true },
  laundry: { mode: 'booking', slotHours: 2, price: '2,30 €', machines: 4, hours: [7, 22], location: null, bookingSystem: null },
  cleaning: { rooms: 'weekdays', common: 'daily' },
  access: 'card+biometric',
  parking: { mode: 'register-plate', spots: null },
  cardReplacementFee: null,
  checkOutTime: null,
  wasteBinsLocation: null,
  smokingArea: 'outdoor-marked',
  emergency: {
    numbers: { general: '112', ambulance: '155', fire: '150', police: '158' },
    receptionPhone: '+421 2 3310 4404',
    addressToRead: 'Stará Vajnorská 39A, Bratislava – Nové Mesto, ubytovňa PRIMA TARIF',
    assemblyPoint: 'parking', assemblyGate: null,
    firstAid: 'reception', defibrillator: null,
  },
  // Miesta v okolí — adresy a odkazy na mapu sú jazykovo neutrálne, popisy sú v <lang>.js.
  places: {
    busStop: { name: 'Stará Vajnorská', lines: ['57', '65'], map: 'Stará Vajnorská, zastávka MHD, Bratislava' },
    tram: { name: 'Zlaté piesky', line: '4', walkMin: 8, walkVerified: false, map: 'Zlaté piesky, zastávka električky, Bratislava' },
    mall: { name: 'Shopping Palace Zlaté piesky', walkMin: 15, map: 'Shopping Palace Zlaté piesky, Cesta na Senec 2/A, Bratislava' },
    grocery: { name: null, candidates: ['Tesco Extra Zlaté piesky', 'Lidl Zlaté piesky'], walkMin: 9, map: 'Tesco Extra Zlaté piesky, Bratislava' },
    pharmacy: { name: null, candidates: ['Lekáreň Dr. Max, Shopping Palace'], walkMin: 8, map: 'Lekáreň Dr. Max Shopping Palace Zlaté piesky' },
    hospital: { name: 'UNB Ružinov', address: 'Ružinovská 6', verified: true, map: 'Univerzitná nemocnica Bratislava Ružinov, Ružinovská 6' },
    gp: { name: null, candidates: ['Poliklinika Vajnorská, Vajnorská 40'], map: 'Poliklinika Vajnorská, Vajnorská 40, Bratislava' },
    post: { name: 'Slovenská pošta', address: 'Cesta na Senec 2A', hours: 'Mon–Sun 8–20', westernUnion: true, map: 'Slovenská pošta, Cesta na Senec 2A, Bratislava' },
    novaPost: { name: 'Nova Post №1', address: 'Dunajská 14', map: 'Nova Post, Dunajská 14, Bratislava' },
    parcelBoxes: { name: null, candidates: ['Packeta Z-BOX / AlzaBox, Shopping Palace'], map: 'Shopping Palace Zlaté piesky' },
    foreignPolice: { name: 'Oddelenie cudzineckej polície Bratislava', address: 'Račianska 62', hours: 'Mon/Wed/Fri 7:30–15:30 · Tue 7:30–15:00 · Thu 7:30–14:00', appointmentRequired: true, map: 'Račianska 62, Bratislava' },
    iom: { name: 'IOM Migration Information Centre', address: 'Grösslingová 35', hours: 'Mon/Tue/Thu 9–12, 13–17', phone: '0850 211 478', telegram: '+421 908 767 853', map: 'Grösslingová 35, Bratislava' },
    embassies: [
      { country: 'UA', name: 'Embassy of Ukraine', address: 'Radvanská 35', map: 'Radvanská 35, Bratislava' },
      { country: 'RS', name: 'Embassy of Serbia', address: 'Búdková 38', map: 'Búdková 38, Bratislava' },
      { country: 'RO', name: 'Embassy of Romania', address: 'Fraňa Kráľa 11', map: 'Fraňa Kráľa 11, Bratislava' },
      { country: 'IN', name: 'Embassy of India', address: 'Dunajská 4, 7th floor', map: 'Dunajská 4, Bratislava' },
      { country: 'VN', name: 'Embassy of Vietnam', address: 'Dunajská 15', map: 'Dunajská 15, Bratislava' },
    ],
    worship: [
      { key: 'orthodox', name: 'Chrám sv. Rastislava (Orthodox)', address: 'Tomášikova, Ružinov', hours: 'Mon–Fri 8:00 · Sat 9:30 · Sun 10:00', verified: false, map: 'Pravoslávny chrám sv. Rastislava, Tomášikova, Bratislava' },
      { key: 'greekCatholic', name: 'Greek Catholic cathedral', address: 'Ulica 29. augusta 7', note: 'Ukrainian-rite liturgies also at St. Rosalia, Lamač', verified: false, map: 'Gréckokatolícka katedrála Povýšenia svätého Kríža, Ulica 29. augusta 7, Bratislava' },
      { key: 'catholic', name: null, address: null, map: null },
      { key: 'mosque', name: 'AYA prayer room', address: 'Bojnícka 18', hours: 'Friday prayer ~13:00', verified: false, map: 'Bojnícka 18, Bratislava' },
    ],
    leisure: [
      { key: 'zlatePiesky', name: 'Zlaté piesky lake', map: 'Zlaté piesky, Bratislava' },
      { key: 'kuchajda', name: 'Kuchajda lake', map: 'Kuchajda, Bratislava' },
      { key: 'gym', name: null, map: null },
    ],
  },
  tickets: { from: '2026-07-01', single: [['30 min', '1,20 €', '1,09 €'], ['60 min', '1,80 €', '1,60 €'], ['24 h', '5,40 €', '4,85 €']], passes: [['30 days', '40,50 €'], ['365 days', '263 €']], fine: ['79 €', '89 €', '99 €'] },
};
